title: Michael Archibald
description: Programming, Economics and Leadership musings
author: Michael Archibald
logo: https://avatars0.githubusercontent.com/u/251132
github: https://github.com/neener54
about: Ruby Software Craftsman

baseurl: "https://neener54.github.io"
url: "https://neener54.github.io"

allowsearch: true

disqus_shortname: neener54
google_analytics: UA-59572507-1

share:
  twitter_username: \micharch54
  fb_appid: 000000000000


enableTags: true
tagarray: [leadership, management, ruby]

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins: [jekyll-paginate, jekyll-gist]

collections:
  resumes:
    section: true
  experiences:
    section: true